### ISSUE TITLE
train.py on colab, using snippets

### ISSUE THREAD

**Issue by yhg8423** [jerrodparker20/RoboticsCourseProject#12]
Hi, I have a question about snippets in README. 
I plan to use your code in colab. To test the code, I executed train.py with your snippets. 
However, train.py is not working well. The result showed that loss is infinite and stats are empty. 
Could I know how to solve the problem?

**Comment by shaktikshri** [comment]
Hi @yhg8423 , the code runs with learners in one set of threads and actors in another parallel set of threads. The stats are reported from the main thread which periodically collects stuff from learner threads buffers. The only reason for stats being empty is when any of the threads run into an exception. Its hard to comment on your colab usage without seeing what snippets you are running. I'd suggest you to setup the environment (for pong) and run the entire train.py with the arguments we've provided in the readme.

**Comment by yhg8423** [comment]
Oh, I see. I will check it. Thank you for your answer!

**Comment by shaktikshri** [comment]
@yhg8423 let us know if you still face issues. We're closing this for now.

**Comment by ghost** [comment]
When I used just one actor, I still get Steps 0 @ 0.0 SPS. Loss inf. Stats.
